In [45]:
import numpy as np

In [46]:
my_list=[-1,0,1]

In [47]:
my_list,type(my_list)

([-1, 0, 1], list)

In [48]:
my_array=np.array(my_list)

In [49]:
my_array,type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [50]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [51]:
matrix,type(matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [52]:
two_array=np.array(matrix)

In [53]:
two_array,type(two_array)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [54]:
tuple={2,0,9}

In [55]:
tuple_array=np.array(tuple)
tuple_array,type(tuple_array)

(array({0, 9, 2}, dtype=object), numpy.ndarray)

In [56]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.arange(3,23,3,dtype=float)

array([ 3.,  6.,  9., 12., 15., 18., 21.])

In [58]:
np.linspace(1,45,45)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45.])

In [59]:
np.linspace(1,25,20,retstep=True)

(array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
         7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
        13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
        19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ]),
 1.263157894736842)

In [60]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [63]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [64]:
np.random

<module 'numpy.random' from 'C:\\Users\\anees\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [65]:
np.random.rand(4)

array([0.45505334, 0.04803949, 0.39458077, 0.4634075 ])

In [66]:
np.random.rand(3,4)

array([[0.59297773, 0.37618797, 0.45757236, 0.30040335],
       [0.38868111, 0.90181909, 0.51167156, 0.10556426],
       [0.00944374, 0.85195217, 0.29735727, 0.05907824]])

In [67]:
np.random.randn(4,4)

array([[-0.03175959,  0.37870407,  1.43126362,  0.73258748],
       [ 0.63286468, -0.52075108, -0.83938558,  2.19250188],
       [ 0.73056167, -0.15535419,  1.24058579, -0.26328434],
       [ 0.20486591, -0.83550034, -1.72565941,  1.28140511]])

In [68]:
np.random.randint(20,250)

91

In [69]:
np.random.randint(1,100,5)

array([85, 95, 32, 10, 41])

In [70]:
np.random.randint(1,100,(5,6))

array([[22, 58, 47, 63, 19, 61],
       [46, 37, 17, 97, 69, 63],
       [65, 13, 82, 95, 80, 76],
       [93, 26, 49, 26,  4, 40],
       [22, 29, 69, 10,  2, 79]])

array methods and attributes:

In [71]:
#generating an array
array_arange=np.arange(16)
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
#generate one more using randint
array_ranint=np.random.randint(0,200,20)
array_ranint

array([100,  85,  56,  11,  30, 145, 115,  49,  79,  73,  49, 171, 178,
       184,  35,  94, 135,  52, 141,  88])

In [74]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
#to find the max value in an array
array_ranint.min()

11

In [77]:
#to find the min value in an array
array_ranint.max()

184

In [78]:
#returns the location of the max value in the array
array_ranint.argmax()


13

In [79]:
#returns the location of the min value in the array
array_ranint.argmin()


3

In [80]:
array_arange.shape

(16,)

In [81]:
array_arange.size

16

In [82]:
array_arange.dtype

dtype('int32')

In [85]:
array_arange.reshape(4,4).shape

(4, 4)